### GET  
GET http://localhost:5086/api/Catalog
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjI0Njg2NTU2NDc1ODFiZGIzY2UzOTUiLCJleHAiOjE3MTM2NjU4OTl9.KJr2rD0PFfeykG3kxypD99ADhbi_TW3fGWTz8RrBnrk

### Send POST request with json body
POST http://localhost:5086/api/Catalog
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjI0Njg2NTU2NDc1ODFiZGIzY2UzOTUiLCJleHAiOjE3MTM2NjU4OTl9.KJr2rD0PFfeykG3kxypD99ADhbi_TW3fGWTz8RrBnrk

{
  "name": "catalog test",
  "description": "test catalog",
  "price": 19.99
}